# 定时任务执行go程序并提交到github
name: github_trend

on:
  schedule:
    # 每天，执行一次
    - cron: "0 1 * * *"

  workflow_dispatch:

jobs:
  github_trend:
    runs-on: ubuntu-latest
    env:
      BAIDU_TRANSLATE_API_KEY: ${{ secrets.BAIDU_TRANSLATE_API_KEY }}
      BAIDU_TRANSLATE_API_ID: ${{ secrets.BAIDU_TRANSLATE_API_ID }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      SMTP_MAIL: ${{ secrets.SMTP_MAIL }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      CLOUDFLARE_ID: ${{ secrets.CLOUDFLARE_ID }}
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
      - name: Run Go program
        run: |
          go version
          go run main.go
      - name: Commit files
        run: |
          git config --local user.email "13028911306@163.com"
          git config --local user.name "jobcher"
          git add .
          git commit -m "update github trend"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: 企业微信通知
        if: always()
        run: |
          set -e
          # 获取 token
          TOKEN=$(curl -s "https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=${{ secrets.WEWORK_CORPID }}&corpsecret=${{ secrets.WEWORK_SECRET }}" | jq -r .access_token)

          STATUS="✅ 成功"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="❌ 失败"
          fi

          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)
          COMMIT_MSG=$(git log -1 --pretty=%s)

          MSG="jobcher博客 热点数据抓取 ${STATUS}\n分支: main\n提交人: ${{ github.actor }}\n提交ID: ${SHORT_SHA}\n说明: ${COMMIT_MSG}"

          curl -s -X POST "https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=$TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
                  \"touser\": \"@all\",
                  \"msgtype\": \"text\",
                  \"agentid\": ${{ secrets.WEWORK_AGENTID }},
                  \"text\": { \"content\": \"$MSG\" },
                  \"safe\": 0
                }"
